swagger: '2.0'
info:
  description: 中台一点资源确认
  version: 1.0.0
  title: 中台一点资源确认Java快速开发平台接口文档
#host: localhost:18884
basePath: /

schemes:
  - http

#认证
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"

tags:
- name: address-controller
  description: 标准地址查询以及地址资源查询接口
- name: city-address-controller
  description: 城市地址查询接口
- name: area-address-controller
  description: 省份地址查询接口
paths:
  "/address/query/{searchContent}":
    get:
      tags:
      - address-controller
      summary: 根据输入地名进行标准地址查询
      operationId: queryUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: searchContent
        in: path
        description: 查询字符串
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/Address"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryAddress":
    post:
      tags:
      - address-controller
      summary: 根据省、本地网和输入地名进行标准地址查询
      operationId: queryAddressUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: request
        description: 用户请求信息
        required: true
        schema:
          "$ref": "#/definitions/RequestOSMC"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ResponseOSMC"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryAddressForWeb":
    post:
      tags:
      - address-controller
      summary: 根据省、本地网和输入地名进行标准地址查询
      operationId: queryAddressForWebUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: request
        description: 用户请求信息
        required: true
        schema:
          "$ref": "#/definitions/RequestOSMC"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ResponseOSMC"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryAll":
    get:
      tags:
      - address-controller
      summary: 获取所有标准地址
      operationId: queryAllUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/Address"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryByDomainAndArea/{domainId}/{searchContent}":
    get:
      tags:
      - address-controller
      summary: 根据省、本地网和输入地名进行标准地址查询
      operationId: queryAddressUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: domainId
        in: path
        description: 省份ID
        required: true
        type: string
      - name: areaId
        in: query
        description: 本地网ID
        required: false
        type: string
      - name: searchContent
        in: path
        description: 查询字符串
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/Address"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryResource/{shardingId}":
    get:
      tags:
      - address-controller
      summary: 根据标准地址查询资源
      operationId: queryResourceUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: shardingId
        in: path
        description: 地址shardingId
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryTestGet":
    get:
      tags:
      - address-controller
      summary: queryTestGet
      operationId: queryTestGetUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/address/queryTestPOST":
    post:
      tags:
      - address-controller
      summary: queryTestPOST
      operationId: queryTestPOSTUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/area/findById":
    get:
      tags:
      - city-address-controller
      summary: 获取所有标准地址
      operationId: findByIdUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: query
        description: id
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/CityAddress"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/area/findall":
    get:
      tags:
      - area-address-controller
      summary: 获取所有标准地址
      operationId: findAllUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/AreaAddress"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  AreaAddress:
    properties:
      code:
        type: string
      id:
        type: integer
        format: int32
      name:
        type: string
  Pagination:
    properties:
      from:
        type: integer
        format: int32
      size:
        type: integer
        format: int32
  CityAddress:
    properties:
      code:
        type: string
      defaultadr:
        type: string
      domainId:
        type: string
      id:
        type: string
      name:
        type: string
      notes:
        type: string
  Address:
    properties:
      full_name:
        type: string
      id:
        type: string
      location_ids:
        type: string
      search_name:
        type: string
      sharding_id:
        type: string
      spec_id:
        type: string
      suggust_name:
        type: string
  ResponseReturn:
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
      status:
        type: string
  AddressResponseData:
    properties:
      addressesList:
        type: array
        items:
          "$ref": "#/definitions/AddressReturn"
      total:
        type: integer
        format: int64
  AddressRequestData:
    properties:
      businessId:
        type: string
      domainCode:
        type: string
      pagination:
        "$ref": "#/definitions/Pagination"
      searchAddress:
        type: string
      shardingCode:
        type: string
  RequestHeader:
    properties:
      layer:
        type: string
      requestTime:
        type: string
      roleId:
        type: string
      senderId:
        type: string
      servicegroup:
        type: string
      zone:
        type: string
  RequestOSMC:
    properties:
      data:
        "$ref": "#/definitions/AddressRequestData"
      head:
        "$ref": "#/definitions/RequestHeader"
  ResponseOSMC:
    properties:
      data:
        "$ref": "#/definitions/AddressResponseData"
      result:
        "$ref": "#/definitions/ResponseReturn"
  AddressReturn:
    properties:
      full_name:
        type: string
      id:
        type: string
      location_ids:
        type: string
      sharding_id:
        type: string
      spec_id:
        type: string
